site_name: Ballance Mapping Tutorial
site_description: 'The tutorial for Ballance mapping.'
site_author: 'yyc12345'
# site_url: 'https://yyc12345.github.io/bpm_wiki/'

# repo_name: 'GameExpCombination/BallanceMappingTutorial'
# repo_url: 'https://github.com/GameExpCombination/BallanceMappingTutorial'

copyright: 'Text is available under the CC-BY-NC-SA 4.0. Supported by GCBA, Chinese Ballance Forum, Ballance Discord Server and BearKidsTeam.'

nav:
    - Language: index.md
    - 简体中文:
        - '前言': 'zh-hans/index.md'
        - 'Virtools教程':
          - '概述': 'zh-hans/virtools/intro.md'
          - '了解Virtools': 'zh-hans/virtools/basic.md'
          - '物件与组': 'zh-hans/virtools/object_group.md'
          - 'Virtools元素概述': 'zh-hans/virtools/elements.md'
          - 'Virtools元素扩展': 'zh-hans/virtools/enhanced_elements.md'
          - '游戏机制与制图': 'zh-hans/virtools/game.md'
        - '3ds Max教程':
          - '概述': 'zh-hans/max/intro.md'
          - '版本差异': 'zh-hans/max/version.md'
          - '注册': 'zh-hans/max/register.md'
          - '基本操作': 'zh-hans/max/basic.md'
          - '建造路面与钢轨（入门）': 'zh-hans/max/road_rail.md'
          - 'NMO文件导入Max': 'zh-hans/max/nmo_import.md'
          - '直接制作路面教程（进阶）': 'zh-hans/max/enhanced_road_rail.md'
        - '版权与许可证': 'zh-hans/license.md'
    - English:
        - 'Introduction': 'en/index.md'
        - 'Virtools tutorial':
          - 'Intorduction': 'en/virtools/intro.md'
          - 'Understand Virtools': 'en/virtools/basic.md'
          - 'Object and group': 'en/virtools/object_group.md'
          - 'Virtools elements': 'en/virtools/elements.md'
          - 'Virtools enhanced elements': 'en/virtools/enhanced_elements.md'
          - 'Game mechanism and mapping': 'en/virtools/game.md'
        - '3ds Max tutorial':
          - 'Intorduction': 'en/max/intro.md'
          - 'Version difference': 'en/max/version.md'
          - 'Register': 'en/max/register.md'
          - 'Basic operation': 'en/max/basic.md'
          - 'Build road and rail': 'en/max/road_rail.md'
          - 'Import NMO file': 'en/max/nmo_import.md'
          - 'Enhanced build road and rail': 'en/max/enhanced_road_rail.md'
        - 'Copyright and license': 'en/license.md'

theme:
  name: 'material'
  font: false
  palette:
    primary: blue
    accent: blue
  language: 'en'
  favicon: './img/favicon.ico'
  feature:
    tabs: true
  logo:
    icon: 'book'

plugins: []

extra:
  social:
    # - type: 'github'
    #   link: 'https://github.com/yyc12345/bpm_wiki'
    - type: 'discord'
      link: 'https://discord.gg/hyarMPm'

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - ./javascript/website.js